/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gov.nasa.race.track.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** represents the state of a track at a given time */
@org.apache.avro.specific.AvroGenerated
public class FullTrackPoint extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8642017513678908697L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FullTrackPoint\",\"namespace\":\"gov.nasa.race.track.avro\",\"doc\":\"represents the state of a track at a given time\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"identifier for this track\"},{\"name\":\"date\",\"type\":\"long\",\"doc\":\"unix epoch for this track point\",\"units\":\"milliseconds\"},{\"name\":\"latitude\",\"type\":\"double\",\"doc\":\"WGS84 latitude of track point\",\"units\":\"degrees\"},{\"name\":\"longitude\",\"type\":\"double\",\"doc\":\"WGS84 longitude of track point\",\"units\":\"degrees\"},{\"name\":\"altitude\",\"type\":\"double\",\"doc\":\"(barometric) altitude of track point\",\"units\":\"meters\"},{\"name\":\"speed\",\"type\":\"double\",\"doc\":\"ground speed at track point\",\"units\":\"m/s\"},{\"name\":\"heading\",\"type\":\"double\",\"doc\":\"heading at track point\",\"units\":\"degrees\"},{\"name\":\"distance\",\"type\":\"double\",\"doc\":\"traveled distance at track point\",\"units\":\"NM\"},{\"name\":\"climbRate\",\"type\":\"double\",\"doc\":\"rate of climb at track point\",\"units\":\"m/s\"},{\"name\":\"acceleration\",\"type\":\"double\",\"doc\":\"ground speed acceleration at track point\",\"units\":\"m/s?\"},{\"name\":\"completed\",\"type\":\"boolean\",\"doc\":\"is last track point for this id\"},{\"name\":\"pointnum\",\"type\":\"int\",\"doc\":\"running number of track point for this track\"},{\"name\":\"amendment\",\"type\":[\"null\",\"string\"],\"doc\":\"optional amendment text for track point\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** identifier for this track */
  @Deprecated public java.lang.CharSequence id;
  /** unix epoch for this track point */
  @Deprecated public long date;
  /** WGS84 latitude of track point */
  @Deprecated public double latitude;
  /** WGS84 longitude of track point */
  @Deprecated public double longitude;
  /** (barometric) altitude of track point */
  @Deprecated public double altitude;
  /** ground speed at track point */
  @Deprecated public double speed;
  /** heading at track point */
  @Deprecated public double heading;
  /** traveled distance at track point */
  @Deprecated public double distance;
  /** rate of climb at track point */
  @Deprecated public double climbRate;
  /** ground speed acceleration at track point */
  @Deprecated public double acceleration;
  /** is last track point for this id */
  @Deprecated public boolean completed;
  /** running number of track point for this track */
  @Deprecated public int pointnum;
  /** optional amendment text for track point */
  @Deprecated public java.lang.CharSequence amendment;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FullTrackPoint() {}

  /**
   * All-args constructor.
   * @param id identifier for this track
   * @param date unix epoch for this track point
   * @param latitude WGS84 latitude of track point
   * @param longitude WGS84 longitude of track point
   * @param altitude (barometric) altitude of track point
   * @param speed ground speed at track point
   * @param heading heading at track point
   * @param distance traveled distance at track point
   * @param climbRate rate of climb at track point
   * @param acceleration ground speed acceleration at track point
   * @param completed is last track point for this id
   * @param pointnum running number of track point for this track
   * @param amendment optional amendment text for track point
   */
  public FullTrackPoint(java.lang.CharSequence id, java.lang.Long date, java.lang.Double latitude, java.lang.Double longitude, java.lang.Double altitude, java.lang.Double speed, java.lang.Double heading, java.lang.Double distance, java.lang.Double climbRate, java.lang.Double acceleration, java.lang.Boolean completed, java.lang.Integer pointnum, java.lang.CharSequence amendment) {
    this.id = id;
    this.date = date;
    this.latitude = latitude;
    this.longitude = longitude;
    this.altitude = altitude;
    this.speed = speed;
    this.heading = heading;
    this.distance = distance;
    this.climbRate = climbRate;
    this.acceleration = acceleration;
    this.completed = completed;
    this.pointnum = pointnum;
    this.amendment = amendment;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return date;
    case 2: return latitude;
    case 3: return longitude;
    case 4: return altitude;
    case 5: return speed;
    case 6: return heading;
    case 7: return distance;
    case 8: return climbRate;
    case 9: return acceleration;
    case 10: return completed;
    case 11: return pointnum;
    case 12: return amendment;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: date = (java.lang.Long)value$; break;
    case 2: latitude = (java.lang.Double)value$; break;
    case 3: longitude = (java.lang.Double)value$; break;
    case 4: altitude = (java.lang.Double)value$; break;
    case 5: speed = (java.lang.Double)value$; break;
    case 6: heading = (java.lang.Double)value$; break;
    case 7: distance = (java.lang.Double)value$; break;
    case 8: climbRate = (java.lang.Double)value$; break;
    case 9: acceleration = (java.lang.Double)value$; break;
    case 10: completed = (java.lang.Boolean)value$; break;
    case 11: pointnum = (java.lang.Integer)value$; break;
    case 12: amendment = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return identifier for this track
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * identifier for this track
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return unix epoch for this track point
   */
  public java.lang.Long getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * unix epoch for this track point
   * @param value the value to set.
   */
  public void setDate(java.lang.Long value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return WGS84 latitude of track point
   */
  public java.lang.Double getLatitude() {
    return latitude;
  }

  /**
   * Sets the value of the 'latitude' field.
   * WGS84 latitude of track point
   * @param value the value to set.
   */
  public void setLatitude(java.lang.Double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return WGS84 longitude of track point
   */
  public java.lang.Double getLongitude() {
    return longitude;
  }

  /**
   * Sets the value of the 'longitude' field.
   * WGS84 longitude of track point
   * @param value the value to set.
   */
  public void setLongitude(java.lang.Double value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'altitude' field.
   * @return (barometric) altitude of track point
   */
  public java.lang.Double getAltitude() {
    return altitude;
  }

  /**
   * Sets the value of the 'altitude' field.
   * (barometric) altitude of track point
   * @param value the value to set.
   */
  public void setAltitude(java.lang.Double value) {
    this.altitude = value;
  }

  /**
   * Gets the value of the 'speed' field.
   * @return ground speed at track point
   */
  public java.lang.Double getSpeed() {
    return speed;
  }

  /**
   * Sets the value of the 'speed' field.
   * ground speed at track point
   * @param value the value to set.
   */
  public void setSpeed(java.lang.Double value) {
    this.speed = value;
  }

  /**
   * Gets the value of the 'heading' field.
   * @return heading at track point
   */
  public java.lang.Double getHeading() {
    return heading;
  }

  /**
   * Sets the value of the 'heading' field.
   * heading at track point
   * @param value the value to set.
   */
  public void setHeading(java.lang.Double value) {
    this.heading = value;
  }

  /**
   * Gets the value of the 'distance' field.
   * @return traveled distance at track point
   */
  public java.lang.Double getDistance() {
    return distance;
  }

  /**
   * Sets the value of the 'distance' field.
   * traveled distance at track point
   * @param value the value to set.
   */
  public void setDistance(java.lang.Double value) {
    this.distance = value;
  }

  /**
   * Gets the value of the 'climbRate' field.
   * @return rate of climb at track point
   */
  public java.lang.Double getClimbRate() {
    return climbRate;
  }

  /**
   * Sets the value of the 'climbRate' field.
   * rate of climb at track point
   * @param value the value to set.
   */
  public void setClimbRate(java.lang.Double value) {
    this.climbRate = value;
  }

  /**
   * Gets the value of the 'acceleration' field.
   * @return ground speed acceleration at track point
   */
  public java.lang.Double getAcceleration() {
    return acceleration;
  }

  /**
   * Sets the value of the 'acceleration' field.
   * ground speed acceleration at track point
   * @param value the value to set.
   */
  public void setAcceleration(java.lang.Double value) {
    this.acceleration = value;
  }

  /**
   * Gets the value of the 'completed' field.
   * @return is last track point for this id
   */
  public java.lang.Boolean getCompleted() {
    return completed;
  }

  /**
   * Sets the value of the 'completed' field.
   * is last track point for this id
   * @param value the value to set.
   */
  public void setCompleted(java.lang.Boolean value) {
    this.completed = value;
  }

  /**
   * Gets the value of the 'pointnum' field.
   * @return running number of track point for this track
   */
  public java.lang.Integer getPointnum() {
    return pointnum;
  }

  /**
   * Sets the value of the 'pointnum' field.
   * running number of track point for this track
   * @param value the value to set.
   */
  public void setPointnum(java.lang.Integer value) {
    this.pointnum = value;
  }

  /**
   * Gets the value of the 'amendment' field.
   * @return optional amendment text for track point
   */
  public java.lang.CharSequence getAmendment() {
    return amendment;
  }

  /**
   * Sets the value of the 'amendment' field.
   * optional amendment text for track point
   * @param value the value to set.
   */
  public void setAmendment(java.lang.CharSequence value) {
    this.amendment = value;
  }

  /**
   * Creates a new FullTrackPoint RecordBuilder.
   * @return A new FullTrackPoint RecordBuilder
   */
  public static gov.nasa.race.track.avro.FullTrackPoint.Builder newBuilder() {
    return new gov.nasa.race.track.avro.FullTrackPoint.Builder();
  }

  /**
   * Creates a new FullTrackPoint RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FullTrackPoint RecordBuilder
   */
  public static gov.nasa.race.track.avro.FullTrackPoint.Builder newBuilder(gov.nasa.race.track.avro.FullTrackPoint.Builder other) {
    return new gov.nasa.race.track.avro.FullTrackPoint.Builder(other);
  }

  /**
   * Creates a new FullTrackPoint RecordBuilder by copying an existing FullTrackPoint instance.
   * @param other The existing instance to copy.
   * @return A new FullTrackPoint RecordBuilder
   */
  public static gov.nasa.race.track.avro.FullTrackPoint.Builder newBuilder(gov.nasa.race.track.avro.FullTrackPoint other) {
    return new gov.nasa.race.track.avro.FullTrackPoint.Builder(other);
  }

  /**
   * RecordBuilder for FullTrackPoint instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FullTrackPoint>
    implements org.apache.avro.data.RecordBuilder<FullTrackPoint> {

    /** identifier for this track */
    private java.lang.CharSequence id;
    /** unix epoch for this track point */
    private long date;
    /** WGS84 latitude of track point */
    private double latitude;
    /** WGS84 longitude of track point */
    private double longitude;
    /** (barometric) altitude of track point */
    private double altitude;
    /** ground speed at track point */
    private double speed;
    /** heading at track point */
    private double heading;
    /** traveled distance at track point */
    private double distance;
    /** rate of climb at track point */
    private double climbRate;
    /** ground speed acceleration at track point */
    private double acceleration;
    /** is last track point for this id */
    private boolean completed;
    /** running number of track point for this track */
    private int pointnum;
    /** optional amendment text for track point */
    private java.lang.CharSequence amendment;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gov.nasa.race.track.avro.FullTrackPoint.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.latitude)) {
        this.latitude = data().deepCopy(fields()[2].schema(), other.latitude);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.longitude)) {
        this.longitude = data().deepCopy(fields()[3].schema(), other.longitude);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.altitude)) {
        this.altitude = data().deepCopy(fields()[4].schema(), other.altitude);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.speed)) {
        this.speed = data().deepCopy(fields()[5].schema(), other.speed);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.heading)) {
        this.heading = data().deepCopy(fields()[6].schema(), other.heading);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.distance)) {
        this.distance = data().deepCopy(fields()[7].schema(), other.distance);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.climbRate)) {
        this.climbRate = data().deepCopy(fields()[8].schema(), other.climbRate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.acceleration)) {
        this.acceleration = data().deepCopy(fields()[9].schema(), other.acceleration);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.completed)) {
        this.completed = data().deepCopy(fields()[10].schema(), other.completed);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.pointnum)) {
        this.pointnum = data().deepCopy(fields()[11].schema(), other.pointnum);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.amendment)) {
        this.amendment = data().deepCopy(fields()[12].schema(), other.amendment);
        fieldSetFlags()[12] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FullTrackPoint instance
     * @param other The existing instance to copy.
     */
    private Builder(gov.nasa.race.track.avro.FullTrackPoint other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.latitude)) {
        this.latitude = data().deepCopy(fields()[2].schema(), other.latitude);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.longitude)) {
        this.longitude = data().deepCopy(fields()[3].schema(), other.longitude);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.altitude)) {
        this.altitude = data().deepCopy(fields()[4].schema(), other.altitude);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.speed)) {
        this.speed = data().deepCopy(fields()[5].schema(), other.speed);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.heading)) {
        this.heading = data().deepCopy(fields()[6].schema(), other.heading);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.distance)) {
        this.distance = data().deepCopy(fields()[7].schema(), other.distance);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.climbRate)) {
        this.climbRate = data().deepCopy(fields()[8].schema(), other.climbRate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.acceleration)) {
        this.acceleration = data().deepCopy(fields()[9].schema(), other.acceleration);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.completed)) {
        this.completed = data().deepCopy(fields()[10].schema(), other.completed);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.pointnum)) {
        this.pointnum = data().deepCopy(fields()[11].schema(), other.pointnum);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.amendment)) {
        this.amendment = data().deepCopy(fields()[12].schema(), other.amendment);
        fieldSetFlags()[12] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * identifier for this track
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * identifier for this track
      * @param value The value of 'id'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * identifier for this track
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * identifier for this track
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * unix epoch for this track point
      * @return The value.
      */
    public java.lang.Long getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * unix epoch for this track point
      * @param value The value of 'date'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setDate(long value) {
      validate(fields()[1], value);
      this.date = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * unix epoch for this track point
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'date' field.
      * unix epoch for this track point
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearDate() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * WGS84 latitude of track point
      * @return The value.
      */
    public java.lang.Double getLatitude() {
      return latitude;
    }

    /**
      * Sets the value of the 'latitude' field.
      * WGS84 latitude of track point
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setLatitude(double value) {
      validate(fields()[2], value);
      this.latitude = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * WGS84 latitude of track point
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'latitude' field.
      * WGS84 latitude of track point
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearLatitude() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * WGS84 longitude of track point
      * @return The value.
      */
    public java.lang.Double getLongitude() {
      return longitude;
    }

    /**
      * Sets the value of the 'longitude' field.
      * WGS84 longitude of track point
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setLongitude(double value) {
      validate(fields()[3], value);
      this.longitude = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * WGS84 longitude of track point
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'longitude' field.
      * WGS84 longitude of track point
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearLongitude() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'altitude' field.
      * (barometric) altitude of track point
      * @return The value.
      */
    public java.lang.Double getAltitude() {
      return altitude;
    }

    /**
      * Sets the value of the 'altitude' field.
      * (barometric) altitude of track point
      * @param value The value of 'altitude'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setAltitude(double value) {
      validate(fields()[4], value);
      this.altitude = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'altitude' field has been set.
      * (barometric) altitude of track point
      * @return True if the 'altitude' field has been set, false otherwise.
      */
    public boolean hasAltitude() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'altitude' field.
      * (barometric) altitude of track point
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearAltitude() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'speed' field.
      * ground speed at track point
      * @return The value.
      */
    public java.lang.Double getSpeed() {
      return speed;
    }

    /**
      * Sets the value of the 'speed' field.
      * ground speed at track point
      * @param value The value of 'speed'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setSpeed(double value) {
      validate(fields()[5], value);
      this.speed = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'speed' field has been set.
      * ground speed at track point
      * @return True if the 'speed' field has been set, false otherwise.
      */
    public boolean hasSpeed() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'speed' field.
      * ground speed at track point
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearSpeed() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'heading' field.
      * heading at track point
      * @return The value.
      */
    public java.lang.Double getHeading() {
      return heading;
    }

    /**
      * Sets the value of the 'heading' field.
      * heading at track point
      * @param value The value of 'heading'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setHeading(double value) {
      validate(fields()[6], value);
      this.heading = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'heading' field has been set.
      * heading at track point
      * @return True if the 'heading' field has been set, false otherwise.
      */
    public boolean hasHeading() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'heading' field.
      * heading at track point
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearHeading() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'distance' field.
      * traveled distance at track point
      * @return The value.
      */
    public java.lang.Double getDistance() {
      return distance;
    }

    /**
      * Sets the value of the 'distance' field.
      * traveled distance at track point
      * @param value The value of 'distance'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setDistance(double value) {
      validate(fields()[7], value);
      this.distance = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'distance' field has been set.
      * traveled distance at track point
      * @return True if the 'distance' field has been set, false otherwise.
      */
    public boolean hasDistance() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'distance' field.
      * traveled distance at track point
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearDistance() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'climbRate' field.
      * rate of climb at track point
      * @return The value.
      */
    public java.lang.Double getClimbRate() {
      return climbRate;
    }

    /**
      * Sets the value of the 'climbRate' field.
      * rate of climb at track point
      * @param value The value of 'climbRate'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setClimbRate(double value) {
      validate(fields()[8], value);
      this.climbRate = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'climbRate' field has been set.
      * rate of climb at track point
      * @return True if the 'climbRate' field has been set, false otherwise.
      */
    public boolean hasClimbRate() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'climbRate' field.
      * rate of climb at track point
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearClimbRate() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'acceleration' field.
      * ground speed acceleration at track point
      * @return The value.
      */
    public java.lang.Double getAcceleration() {
      return acceleration;
    }

    /**
      * Sets the value of the 'acceleration' field.
      * ground speed acceleration at track point
      * @param value The value of 'acceleration'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setAcceleration(double value) {
      validate(fields()[9], value);
      this.acceleration = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'acceleration' field has been set.
      * ground speed acceleration at track point
      * @return True if the 'acceleration' field has been set, false otherwise.
      */
    public boolean hasAcceleration() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'acceleration' field.
      * ground speed acceleration at track point
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearAcceleration() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'completed' field.
      * is last track point for this id
      * @return The value.
      */
    public java.lang.Boolean getCompleted() {
      return completed;
    }

    /**
      * Sets the value of the 'completed' field.
      * is last track point for this id
      * @param value The value of 'completed'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setCompleted(boolean value) {
      validate(fields()[10], value);
      this.completed = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'completed' field has been set.
      * is last track point for this id
      * @return True if the 'completed' field has been set, false otherwise.
      */
    public boolean hasCompleted() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'completed' field.
      * is last track point for this id
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearCompleted() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'pointnum' field.
      * running number of track point for this track
      * @return The value.
      */
    public java.lang.Integer getPointnum() {
      return pointnum;
    }

    /**
      * Sets the value of the 'pointnum' field.
      * running number of track point for this track
      * @param value The value of 'pointnum'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setPointnum(int value) {
      validate(fields()[11], value);
      this.pointnum = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'pointnum' field has been set.
      * running number of track point for this track
      * @return True if the 'pointnum' field has been set, false otherwise.
      */
    public boolean hasPointnum() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'pointnum' field.
      * running number of track point for this track
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearPointnum() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'amendment' field.
      * optional amendment text for track point
      * @return The value.
      */
    public java.lang.CharSequence getAmendment() {
      return amendment;
    }

    /**
      * Sets the value of the 'amendment' field.
      * optional amendment text for track point
      * @param value The value of 'amendment'.
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder setAmendment(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.amendment = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'amendment' field has been set.
      * optional amendment text for track point
      * @return True if the 'amendment' field has been set, false otherwise.
      */
    public boolean hasAmendment() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'amendment' field.
      * optional amendment text for track point
      * @return This builder.
      */
    public gov.nasa.race.track.avro.FullTrackPoint.Builder clearAmendment() {
      amendment = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    public FullTrackPoint build() {
      try {
        FullTrackPoint record = new FullTrackPoint();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.date = fieldSetFlags()[1] ? this.date : (java.lang.Long) defaultValue(fields()[1]);
        record.latitude = fieldSetFlags()[2] ? this.latitude : (java.lang.Double) defaultValue(fields()[2]);
        record.longitude = fieldSetFlags()[3] ? this.longitude : (java.lang.Double) defaultValue(fields()[3]);
        record.altitude = fieldSetFlags()[4] ? this.altitude : (java.lang.Double) defaultValue(fields()[4]);
        record.speed = fieldSetFlags()[5] ? this.speed : (java.lang.Double) defaultValue(fields()[5]);
        record.heading = fieldSetFlags()[6] ? this.heading : (java.lang.Double) defaultValue(fields()[6]);
        record.distance = fieldSetFlags()[7] ? this.distance : (java.lang.Double) defaultValue(fields()[7]);
        record.climbRate = fieldSetFlags()[8] ? this.climbRate : (java.lang.Double) defaultValue(fields()[8]);
        record.acceleration = fieldSetFlags()[9] ? this.acceleration : (java.lang.Double) defaultValue(fields()[9]);
        record.completed = fieldSetFlags()[10] ? this.completed : (java.lang.Boolean) defaultValue(fields()[10]);
        record.pointnum = fieldSetFlags()[11] ? this.pointnum : (java.lang.Integer) defaultValue(fields()[11]);
        record.amendment = fieldSetFlags()[12] ? this.amendment : (java.lang.CharSequence) defaultValue(fields()[12]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
