/*
 * Copyright (c) 2016, United States Government, as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All rights reserved.
 *
 * The RACE - Runtime for Airspace Concept Evaluation platform is licensed
 * under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dds;


/**
* dds/FlightRecord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from race-data/src/main/idl/FlightRecord.idl
* Thursday, September 1, 2016 7:35:40 PM PDT
*/

public final class FlightRecord implements org.omg.CORBA.portable.IDLEntity
{
  public String cs = null;
  public double lat = (double)0;
  public double lon = (double)0;
  public double alt = (double)0;
  public double speed = (double)0;
  public double heading = (double)0;
  public long date = (long)0;

  public FlightRecord ()
  {
  } // ctor

  public FlightRecord (String _cs, double _lat, double _lon, double _alt, double _speed, double _heading, long _date)
  {
    cs = _cs;
    lat = _lat;
    lon = _lon;
    alt = _alt;
    speed = _speed;
    heading = _heading;
    date = _date;
  } // ctor

} // class FlightRecord


