[package]
name = "odin_dem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "odin_dem"
path = "src/bin/odin_dem.rs"


[dependencies]

# our ODIN crates
odin_common = { path = "../odin_common" }
odin_gdal = { path = "../odin_gdal" }

gdal-sys = { version = "0.9.0", features = ["bindgen"] }
gdal = { version = "0.15.0" }
geo = { version = "0.26.0", features = ["proj", "serde"] }
lazy_static = "1.4.0"


