/*
 * Copyright (c) 2016, United States Government, as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All rights reserved.
 *
 * The RACE - Runtime for Airspace Concept Evaluation platform is licensed
 * under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dds;

/**
* dds/FlightRecordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from race-data/src/main/idl/FlightRecord.idl
* Thursday, September 1, 2016 7:35:40 PM PDT
*/

public final class FlightRecordHolder implements org.omg.CORBA.portable.Streamable
{
  public dds.FlightRecord value = null;

  public FlightRecordHolder ()
  {
  }

  public FlightRecordHolder (dds.FlightRecord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dds.FlightRecordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dds.FlightRecordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dds.FlightRecordHelper.type ();
  }

}
