#!/bin/bash

DIR="$(dirname ${BASH_SOURCE[0]})"
SCRIPT=$DIR/../test-tools/kafka-server/target/universal/stage/bin/kafkaserver

if [ -x $SCRIPT ]; then
  $SCRIPT $@
else
  echo "executable does not exist, run sbt kafkaServer/stage"
fi

