#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
if [ -h "$SOURCE" ]; then
  SOURCE="$(readlink "$SOURCE")"
fi
DIR="$(dirname $SOURCE)"

SCRIPT=$DIR/../target/universal/stage/bin/race

# workaround for outdated JOGL distribution which is not Java 9 aware
export JAVA_OPTS="$JAVA_OPTS --add-opens java.desktop/sun.awt=ALL-UNNAMED"

# workaround for broken Java fullscreen support on macOS
if [[ "$OSTYPE" == darwin* ]]; then
  export JAVA_OPTS="$JAVA_OPTS --add-opens java.desktop/com.apple.eawt=ALL-UNNAMED"
fi
 

if [ -x $SCRIPT ]; then
  $SCRIPT $@
else
  echo "script $SCRIPT does not exist, run sbt stage"
fi

