#!/bin/bash

DIR="$(dirname ${BASH_SOURCE[0]})"
SCRIPT=$DIR/../test-tools/zk-server/target/universal/stage/bin/zkserver

if [ -x $SCRIPT ]; then
  $SCRIPT $@
else
  echo "executable does not exist, run sbt zkServer/stage"
fi

