[package]
name = "opendata_splitter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
geojson = "0.24.1"
lazy_static = "1.4.0"
serde_json = "1.0.103"
structopt = "0.3.26"
