/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gov.nasa.race.archive;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroTestRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2091590274666857696L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroTestRecord\",\"namespace\":\"gov.nasa.race.archive\",\"fields\":[{\"name\":\"str\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence str;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroTestRecord() {}

  /**
   * All-args constructor.
   * @param str The new value for str
   */
  public AvroTestRecord(java.lang.CharSequence str) {
    this.str = str;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return str;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: str = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'str' field.
   * @return The value of the 'str' field.
   */
  public java.lang.CharSequence getStr() {
    return str;
  }

  /**
   * Sets the value of the 'str' field.
   * @param value the value to set.
   */
  public void setStr(java.lang.CharSequence value) {
    this.str = value;
  }

  /**
   * Creates a new AvroTestRecord RecordBuilder.
   * @return A new AvroTestRecord RecordBuilder
   */
  public static gov.nasa.race.archive.AvroTestRecord.Builder newBuilder() {
    return new gov.nasa.race.archive.AvroTestRecord.Builder();
  }

  /**
   * Creates a new AvroTestRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroTestRecord RecordBuilder
   */
  public static gov.nasa.race.archive.AvroTestRecord.Builder newBuilder(gov.nasa.race.archive.AvroTestRecord.Builder other) {
    return new gov.nasa.race.archive.AvroTestRecord.Builder(other);
  }

  /**
   * Creates a new AvroTestRecord RecordBuilder by copying an existing AvroTestRecord instance.
   * @param other The existing instance to copy.
   * @return A new AvroTestRecord RecordBuilder
   */
  public static gov.nasa.race.archive.AvroTestRecord.Builder newBuilder(gov.nasa.race.archive.AvroTestRecord other) {
    return new gov.nasa.race.archive.AvroTestRecord.Builder(other);
  }

  /**
   * RecordBuilder for AvroTestRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroTestRecord>
    implements org.apache.avro.data.RecordBuilder<AvroTestRecord> {

    private java.lang.CharSequence str;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gov.nasa.race.archive.AvroTestRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.str)) {
        this.str = data().deepCopy(fields()[0].schema(), other.str);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroTestRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(gov.nasa.race.archive.AvroTestRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.str)) {
        this.str = data().deepCopy(fields()[0].schema(), other.str);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'str' field.
      * @return The value.
      */
    public java.lang.CharSequence getStr() {
      return str;
    }

    /**
      * Sets the value of the 'str' field.
      * @param value The value of 'str'.
      * @return This builder.
      */
    public gov.nasa.race.archive.AvroTestRecord.Builder setStr(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.str = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'str' field has been set.
      * @return True if the 'str' field has been set, false otherwise.
      */
    public boolean hasStr() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'str' field.
      * @return This builder.
      */
    public gov.nasa.race.archive.AvroTestRecord.Builder clearStr() {
      str = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AvroTestRecord build() {
      try {
        AvroTestRecord record = new AvroTestRecord();
        record.str = fieldSetFlags()[0] ? this.str : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
